version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: docker-todo-db
    ports:
      - 5432:5432
    volumes:
      - ./dbscripts:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data
  web:
    build:
      context: ./todo-vue
    volumes:
      - ./todo-vue:/web
      - /web/node_modules
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
  backend-go:
    build:
      context: ./backend-go
    depends_on:
      - postgres
    volumes:
      - ./backend-go:/go-server
    ports:
      - 3000:3000
  backend-node:
    build:
      context: ./backend-node
    volumes:
      - ./backend-node:/node-server
      - /node-server/node_modules
    depends_on:
      - postgres
      - web
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
      - PORT=3000
      - DBHOST=postgres
    ports:
      - 3000:3000
